[package]
name = "eidolon-auth"
version = "0.2.0"
description = "Binary authentication protocol for network connections abstracted from encryption"
keywords = ["cyphernet", "privacy", "euthentification", "network", "p2p"]
categories = ["network-programming", "cryptography"]
readme = "README.md"
authors = { workspace = true }
homepage = { workspace = true }
repository = { workspace = true }
rust-version = { workspace = true }
edition = { workspace = true }
license = { workspace = true }

[lib]
name = "eidolon"

[dependencies]
amplify = { workspace = true }
cyphergraphy = { workspace = true }

[package.metadata.docs.rs]
all-features = true
rustc-args = ["--cfg", "docsrs"]
